name: Testing artifacts

jobs:
  - job: first
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: |
          echo "first" > first.txt
        displayName: "Build"
      - script: |
          ls $BUILD_SOURCESDIRECTORY
        displayName: "Show sources"
      - script: |
          cp $BUILD_SOURCESDIRECTORY/first.txt $BUILD_ARTIFACTSTAGINGDIRECTORY
        displayName: "Move file to staging"
      - task: PublishPipelineArtifact@0
        inpurts:
          artifactName: "first"
          targetPath: "$(Build.ArtifactStagingDirectory)/first.txt"
        displayName: "Upload to artifacts"
